-- Default ticker universe seed.
-- Run once per new user with their user_id substituted in. The web onboarding flow
-- should call a wrapper RPC `seed_default_universe(uuid)` that executes these inserts.

-- ───────────────────────────── S&P 500 Top 60 ────────────────────────
-- Curated mega/large-cap focus list across sectors. NYSE/NASDAQ tickers, no suffix.
-- :user_id is the placeholder.
insert into public.tickers (user_id, symbol, exchange, name, group_tag) values
  (:'user_id', 'AAPL',  'NASDAQ', 'Apple Inc.',                 'sp500_top60'),
  (:'user_id', 'MSFT',  'NASDAQ', 'Microsoft Corp.',            'sp500_top60'),
  (:'user_id', 'NVDA',  'NASDAQ', 'NVIDIA Corp.',               'sp500_top60'),
  (:'user_id', 'GOOGL', 'NASDAQ', 'Alphabet Inc. (A)',          'sp500_top60'),
  (:'user_id', 'AMZN',  'NASDAQ', 'Amazon.com Inc.',            'sp500_top60'),
  (:'user_id', 'META',  'NASDAQ', 'Meta Platforms',             'sp500_top60'),
  (:'user_id', 'TSLA',  'NASDAQ', 'Tesla Inc.',                 'sp500_top60'),
  (:'user_id', 'BRK.B', 'NYSE',   'Berkshire Hathaway (B)',     'sp500_top60'),
  (:'user_id', 'AVGO',  'NASDAQ', 'Broadcom Inc.',              'sp500_top60'),
  (:'user_id', 'JPM',   'NYSE',   'JPMorgan Chase & Co.',       'sp500_top60'),
  (:'user_id', 'V',     'NYSE',   'Visa Inc.',                  'sp500_top60'),
  (:'user_id', 'UNH',   'NYSE',   'UnitedHealth Group',         'sp500_top60'),
  (:'user_id', 'XOM',   'NYSE',   'Exxon Mobil Corp.',          'sp500_top60'),
  (:'user_id', 'WMT',   'NYSE',   'Walmart Inc.',               'sp500_top60'),
  (:'user_id', 'LLY',   'NYSE',   'Eli Lilly & Co.',            'sp500_top60'),
  (:'user_id', 'JNJ',   'NYSE',   'Johnson & Johnson',          'sp500_top60'),
  (:'user_id', 'MA',    'NYSE',   'Mastercard Inc.',            'sp500_top60'),
  (:'user_id', 'PG',    'NYSE',   'Procter & Gamble',           'sp500_top60'),
  (:'user_id', 'ORCL',  'NYSE',   'Oracle Corp.',               'sp500_top60'),
  (:'user_id', 'HD',    'NYSE',   'Home Depot Inc.',            'sp500_top60'),
  (:'user_id', 'COST',  'NASDAQ', 'Costco Wholesale',           'sp500_top60'),
  (:'user_id', 'CVX',   'NYSE',   'Chevron Corp.',              'sp500_top60'),
  (:'user_id', 'ABBV',  'NYSE',   'AbbVie Inc.',                'sp500_top60'),
  (:'user_id', 'MRK',   'NYSE',   'Merck & Co.',                'sp500_top60'),
  (:'user_id', 'BAC',   'NYSE',   'Bank of America',            'sp500_top60'),
  (:'user_id', 'KO',    'NYSE',   'Coca-Cola Co.',              'sp500_top60'),
  (:'user_id', 'PEP',   'NASDAQ', 'PepsiCo Inc.',               'sp500_top60'),
  (:'user_id', 'NFLX',  'NASDAQ', 'Netflix Inc.',               'sp500_top60'),
  (:'user_id', 'TMO',   'NYSE',   'Thermo Fisher Scientific',   'sp500_top60'),
  (:'user_id', 'ADBE',  'NASDAQ', 'Adobe Inc.',                 'sp500_top60'),
  (:'user_id', 'ABT',   'NYSE',   'Abbott Laboratories',        'sp500_top60'),
  (:'user_id', 'CRM',   'NYSE',   'Salesforce Inc.',            'sp500_top60'),
  (:'user_id', 'DIS',   'NYSE',   'Walt Disney Co.',            'sp500_top60'),
  (:'user_id', 'CSCO',  'NASDAQ', 'Cisco Systems',              'sp500_top60'),
  (:'user_id', 'MCD',   'NYSE',   'McDonald''s Corp.',          'sp500_top60'),
  (:'user_id', 'ACN',   'NYSE',   'Accenture plc',              'sp500_top60'),
  (:'user_id', 'WFC',   'NYSE',   'Wells Fargo & Co.',          'sp500_top60'),
  (:'user_id', 'INTC',  'NASDAQ', 'Intel Corp.',                'sp500_top60'),
  (:'user_id', 'TMUS',  'NASDAQ', 'T-Mobile US',                'sp500_top60'),
  (:'user_id', 'LIN',   'NYSE',   'Linde plc',                  'sp500_top60'),
  (:'user_id', 'DHR',   'NYSE',   'Danaher Corp.',              'sp500_top60'),
  (:'user_id', 'AMD',   'NASDAQ', 'Advanced Micro Devices',     'sp500_top60'),
  (:'user_id', 'TXN',   'NASDAQ', 'Texas Instruments',          'sp500_top60'),
  (:'user_id', 'PFE',   'NYSE',   'Pfizer Inc.',                'sp500_top60'),
  (:'user_id', 'UNP',   'NYSE',   'Union Pacific Corp.',        'sp500_top60'),
  (:'user_id', 'IBM',   'NYSE',   'IBM Corp.',                  'sp500_top60'),
  (:'user_id', 'CAT',   'NYSE',   'Caterpillar Inc.',           'sp500_top60'),
  (:'user_id', 'QCOM',  'NASDAQ', 'Qualcomm Inc.',              'sp500_top60'),
  (:'user_id', 'BA',    'NYSE',   'Boeing Co.',                 'sp500_top60'),
  (:'user_id', 'HON',   'NASDAQ', 'Honeywell International',    'sp500_top60'),
  (:'user_id', 'GS',    'NYSE',   'Goldman Sachs Group',        'sp500_top60'),
  (:'user_id', 'NKE',   'NYSE',   'Nike Inc.',                  'sp500_top60'),
  (:'user_id', 'GE',    'NYSE',   'GE Aerospace',               'sp500_top60'),
  (:'user_id', 'PYPL',  'NASDAQ', 'PayPal Holdings',            'sp500_top60'),
  (:'user_id', 'BLK',   'NYSE',   'BlackRock Inc.',             'sp500_top60'),
  (:'user_id', 'SBUX',  'NASDAQ', 'Starbucks Corp.',            'sp500_top60'),
  (:'user_id', 'AMAT',  'NASDAQ', 'Applied Materials',          'sp500_top60'),
  (:'user_id', 'NOW',   'NYSE',   'ServiceNow Inc.',            'sp500_top60'),
  (:'user_id', 'AXP',   'NYSE',   'American Express Co.',       'sp500_top60'),
  (:'user_id', 'PLTR',  'NYSE',   'Palantir Technologies',      'sp500_top60'),
  (:'user_id', 'BKNG',  'NASDAQ', 'Booking Holdings',           'sp500_top60')
on conflict (user_id, symbol) do nothing;

-- ───────────────────────────── DAX 40 ────────────────────────────────
-- Yahoo Finance uses the .DE suffix for XETRA-listed DAX tickers.
insert into public.tickers (user_id, symbol, exchange, name, group_tag) values
  (:'user_id', 'SAP.DE',  'XETRA', 'SAP SE',                       'dax40'),
  (:'user_id', 'SIE.DE',  'XETRA', 'Siemens AG',                   'dax40'),
  (:'user_id', 'ALV.DE',  'XETRA', 'Allianz SE',                   'dax40'),
  (:'user_id', 'DTE.DE',  'XETRA', 'Deutsche Telekom AG',          'dax40'),
  (:'user_id', 'MUV2.DE', 'XETRA', 'Munich Re',                    'dax40'),
  (:'user_id', 'AIR.DE',  'XETRA', 'Airbus SE',                    'dax40'),
  (:'user_id', 'BAS.DE',  'XETRA', 'BASF SE',                      'dax40'),
  (:'user_id', 'BMW.DE',  'XETRA', 'BMW AG',                       'dax40'),
  (:'user_id', 'MBG.DE',  'XETRA', 'Mercedes-Benz Group',          'dax40'),
  (:'user_id', 'VOW3.DE', 'XETRA', 'Volkswagen AG (Pref)',         'dax40'),
  (:'user_id', 'DBK.DE',  'XETRA', 'Deutsche Bank AG',             'dax40'),
  (:'user_id', 'DB1.DE',  'XETRA', 'Deutsche Boerse AG',           'dax40'),
  (:'user_id', 'BAYN.DE', 'XETRA', 'Bayer AG',                     'dax40'),
  (:'user_id', 'IFX.DE',  'XETRA', 'Infineon Technologies',        'dax40'),
  (:'user_id', 'ADS.DE',  'XETRA', 'Adidas AG',                    'dax40'),
  (:'user_id', 'EOAN.DE', 'XETRA', 'E.ON SE',                      'dax40'),
  (:'user_id', 'RWE.DE',  'XETRA', 'RWE AG',                       'dax40'),
  (:'user_id', 'HEN3.DE', 'XETRA', 'Henkel AG (Pref)',             'dax40'),
  (:'user_id', 'MRK.DE',  'XETRA', 'Merck KGaA',                   'dax40'),
  (:'user_id', 'LIN.DE',  'XETRA', 'Linde plc',                    'dax40'),
  (:'user_id', 'FRE.DE',  'XETRA', 'Fresenius SE',                 'dax40'),
  (:'user_id', 'CBK.DE',  'XETRA', 'Commerzbank AG',               'dax40'),
  (:'user_id', 'PAH3.DE', 'XETRA', 'Porsche SE',                   'dax40'),
  (:'user_id', 'P911.DE', 'XETRA', 'Porsche AG',                   'dax40'),
  (:'user_id', 'BEI.DE',  'XETRA', 'Beiersdorf AG',                'dax40'),
  (:'user_id', 'CON.DE',  'XETRA', 'Continental AG',               'dax40'),
  (:'user_id', 'HEI.DE',  'XETRA', 'Heidelberg Materials',         'dax40'),
  (:'user_id', 'MTX.DE',  'XETRA', 'MTU Aero Engines',             'dax40'),
  (:'user_id', 'QIA.DE',  'XETRA', 'Qiagen N.V.',                  'dax40'),
  (:'user_id', 'RHM.DE',  'XETRA', 'Rheinmetall AG',               'dax40'),
  (:'user_id', 'SHL.DE',  'XETRA', 'Siemens Healthineers',         'dax40'),
  (:'user_id', 'ENR.DE',  'XETRA', 'Siemens Energy',               'dax40'),
  (:'user_id', 'SY1.DE',  'XETRA', 'Symrise AG',                   'dax40'),
  (:'user_id', 'VNA.DE',  'XETRA', 'Vonovia SE',                   'dax40'),
  (:'user_id', 'ZAL.DE',  'XETRA', 'Zalando SE',                   'dax40'),
  (:'user_id', 'HNR1.DE', 'XETRA', 'Hannover Rueck SE',            'dax40'),
  (:'user_id', 'DTG.DE',  'XETRA', 'Daimler Truck Holding',        'dax40'),
  (:'user_id', 'SRT3.DE', 'XETRA', 'Sartorius AG (Pref)',          'dax40'),
  (:'user_id', 'BNR.DE',  'XETRA', 'Brenntag SE',                  'dax40'),
  (:'user_id', 'P&G.DE',  'XETRA', 'Procter & Gamble (DE)',        'dax40')
on conflict (user_id, symbol) do nothing;
